# setup for clock, when run in simulation, gazebo is the only clock source
- gz_topic_name: "/clock"
  gz_type_name: "gz.msgs.Clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  lazy: false
  direction: GZ_TO_ROS

# setup for lidar 2d sensor, the 1D array data
- gz_topic_name: "/world/baylands/model/alpha_minus_1_0/link/link/sensor/lidar_2d_v2/scan"
  gz_type_name: "gz.msgs.LaserScan"
  ros_topic_name: "sensor/lidar_2d/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  lazy: true
  direction: GZ_TO_ROS
