# setup for clock, when run in simulation, gazebo is the only clock source
- gz_topic_name: "/clock"
  gz_type_name: "gz.msgs.Clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  lazy: false
  direction: GZ_TO_ROS

# Contact sensor 
- gz_topic_name: "/world/obstacle_tunnel/model/alpha_minus_2_0/link/base_link/sensor/alpha_body_contact/contact"
  gz_type_name: "gz.msgs.Contacts"
  ros_topic_name: "sensor/contact_body/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  lazy: true
  direction: GZ_TO_ROS

- gz_topic_name: "/world/obstacle_tunnel/model/alpha_minus_2_0/link/rotor_0/sensor/alpha_rotor_0_contact/contact"
  gz_type_name: "gz.msgs.Contacts"
  ros_topic_name: "sensor/contact_rotor0/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  lazy: true
  direction: GZ_TO_ROS

- gz_topic_name: "/world/obstacle_tunnel/model/alpha_minus_2_0/link/rotor_1/sensor/alpha_rotor_1_contact/contact"
  gz_type_name: "gz.msgs.Contacts"
  ros_topic_name: "sensor/contact_rotor1/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  lazy: true
  direction: GZ_TO_ROS

- gz_topic_name: "/world/obstacle_tunnel/model/alpha_minus_2_0/link/rotor_2/sensor/alpha_rotor_2_contact/contact"
  gz_type_name: "gz.msgs.Contacts"
  ros_topic_name: "sensor/contact_rotor2/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  lazy: true
  direction: GZ_TO_ROS

- gz_topic_name: "/world/obstacle_tunnel/model/alpha_minus_2_0/link/rotor_3/sensor/alpha_rotor_3_contact/contact"
  gz_type_name: "gz.msgs.Contacts"
  ros_topic_name: "sensor/contact_rotor3/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  lazy: true
  direction: GZ_TO_ROS

# Lidar 1d
- gz_topic_name: "/alpha_lidar_down/scan"
  gz_type_name: "gz.msgs.LaserScan"
  ros_topic_name: "sensor/lidar_1d_down/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  lazy: true
  direction: GZ_TO_ROS

# Lidar 2d
- gz_topic_name: "/world/obstacle_tunnel/model/alpha_minus_2_0/link/link/sensor/lidar_2d_v2/scan"
  gz_type_name: "gz.msgs.LaserScan"
  ros_topic_name: "sensor/lidar_2d/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  lazy: true
  direction: GZ_TO_ROS
  
# Depth camera
- gz_topic_name: "/alpha_depth_cam/camera/image"
  gz_type_name: "gz.msgs.Image"
  ros_topic_name: "sensor/depth_cam/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  lazy: true
  direction: GZ_TO_ROS

# RGB Camera
- gz_topic_name: "/alpha_cam/camera/image"
  gz_type_name: "gz.msgs.Image"
  ros_topic_name: "sensor/rgb_cam/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  lazy: true
  direction: GZ_TO_ROS

# Gimbal camera
- gz_topic_name: "/gimbal/camera/image"
  gz_type_name: "gz.msgs.Image"
  ros_topic_name: "sensor/gimbal_cam/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  lazy: true
  direction: GZ_TO_ROS

# Overview camera
- gz_topic_name: "/alpha_cam_overview/camera/image"
  gz_type_name: "gz.msgs.Image"
  ros_topic_name: "sensor/overview_cam/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  lazy: true
  direction: GZ_TO_ROS
